name: Continuous Integration

on: [push]

jobs:
  rust-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - run: mkdir build && touch build/index.html

      - uses: actions-rs/cargo@v1 
        with:
          command: clippy
          args: -- -D warnings

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - uses: actions-rs/cargo@v1
        with:
          command: build

      - uses: actions-rs/cargo@v1
        with:
          command: test

  spa-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy
        
      - name: Install wasm-pack
        uses: actions-rs/cargo@v1 
        with:
          command: install
          args: wasm-pack

      - name: Build WASM
        run: npm run build:wasm

      - name: Install Modules
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build